function D2e = ABS_D2ematrix(R,lambda_star,omega)
%ABS_D2ematrix
%    D2e = ABS_D2ematrix(R,LAMBDA_STAR,OMEGA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Apr-2024 17:45:38

D2e = [0.0,0.0,omega,(lambda_star-1.0)./R];
end
