function C = ABS_Cmatrix(nu_w)
%ABS_Cmatrix
%    C = ABS_Cmatrix(NU_W)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2023 16:38:01

C = reshape([0.0,1.0,nu_w+1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
