function Ce = ABS_Cematrix(R,lambda_star,nu_w)
%ABS_Cematrix
%    Ce = ABS_Cematrix(R,LAMBDA_STAR,NU_W)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2023 16:38:01

Ce = [(lambda_star-1.0)./R,nu_w+1.0,0.0,0.0,0.0];
