function D2 = ABS_D2matrix(omega)
%ABS_D2matrix
%    D2 = ABS_D2matrix(OMEGA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    23-May-2024 21:13:49

D2 = reshape([0.0,0.0,0.0,0.0,omega,0.0,0.0,1.0],[2,4]);
end
