function D2e = ABS_D2ematrix(R,lambda_star,nu_v,omega,v)
%ABS_D2ematrix
%    D2e = ABS_D2ematrix(R,LAMBDA_STAR,NU_V,OMEGA,V)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-May-2024 10:30:35

t2 = 1.0./R;
D2e = [0.0,0.0,omega,-t2.*(lambda_star+1.0),-t2.*(nu_v+v)];
end
