function B1 = ABS_B1matrix(J)
%ABS_B1matrix
%    B1 = ABS_B1matrix(J)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    23-May-2024 21:13:49

B1 = [0.0;-1.0./J;0.0;0.0;0.0];
end
