function D2 = ABS_D2matrix(omega)
%ABS_D2matrix
%    D2 = ABS_D2matrix(OMEGA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2023 16:38:01

D2 = reshape([0.0,0.0,0.0,0.0,omega,0.0,0.0,1.0],[2,4]);
