function A = ABS_Amatrix(Cd,J,R,m,omega,slope,theta1,theta2,theta3,v,wind)
%ABS_Amatrix
%    A = ABS_Amatrix(Cd,J,R,M,OMEGA,SLOPE,THETA1,THETA2,THETA3,V,WIND)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-May-2024 23:32:30

t2 = cos(slope);
t3 = abs(v);
t4 = sign(v);
t5 = R.*omega;
t6 = 1.0./J;
t7 = 1.0./v;
t8 = t7.^2;
t9 = -t5;
t10 = 1.0./t3;
t12 = t7.*theta3;
t13 = -t7;
t11 = t10.^2;
t14 = t9+v;
t15 = R.*t12;
t19 = t13.*(t5-v);
t16 = abs(t14);
t17 = sign(t14);
t21 = dirac(t19);
t22 = sign(t19);
t24 = t10.*t16.*theta2;
t25 = t10.*t17.*theta2;
t26 = t4.*t11.*t16.*theta2;
t27 = -t24;
t29 = -t26;
t28 = exp(t27);
t32 = t25+t29;
t31 = t28-1.0;
t34 = R.*t22.*t25.*t28.*theta1;
t37 = t22.*t28.*t32.*theta1;
t33 = R.*t7.*t21.*t31.*theta1.*2.0;
t35 = -t34;
t38 = t15+t33+t35;
mt1 = [t2.*(t12-t37+t8.*theta3.*(t5-v)+t21.*t31.*theta1.*(t7+t8.*(t5-v)).*2.0).*(9.81e+2./1.0e+2)-(Cd.*(v.*2.0-wind.*2.0))./m,R.*m.*t2.*t6.*(t12-t37+t8.*theta3.*(t5-v)+t21.*t31.*theta1.*(t7+t8.*(t5-v)).*2.0).*(-9.81e+2./1.0e+2),0.0,0.0,0.0,t2.*t38.*(-9.81e+2./1.0e+2),R.*m.*t2.*t6.*t38.*(9.81e+2./1.0e+2),0.0,0.0,0.0,t2.*t22.*t31.*(9.81e+2./1.0e+2),R.*m.*t2.*t6.*t22.*t31.*(-9.81e+2./1.0e+2),0.0,0.0,0.0,t2.*t10.*t16.*t22.*t28.*theta1.*(-9.81e+2./1.0e+2),R.*m.*t2.*t6.*t10.*t16.*t22.*t28.*theta1.*(9.81e+2./1.0e+2),0.0,0.0];
mt2 = [0.0,t2.*t7.*(t5-v).*(-9.81e+2./1.0e+2),R.*m.*t2.*t6.*t7.*(t5-v).*(9.81e+2./1.0e+2),0.0,0.0,0.0];
A = reshape([mt1,mt2],5,5);
end
