function A = ABS_Amatrix(Cd,J,R,m,omega,slope,theta1,theta2,theta3,v,wind)
%ABS_Amatrix
%    A = ABS_Amatrix(Cd,J,R,M,OMEGA,SLOPE,THETA1,THETA2,THETA3,V,WIND)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Apr-2024 16:48:08

t2 = cos(slope);
t3 = abs(v);
t4 = sign(v);
t5 = R.*omega;
t6 = 1.0./J;
t7 = 1.0./v;
t8 = t7.^2;
t9 = -t5;
t10 = 1.0./t3;
t12 = t7.*theta3;
t13 = -t7;
t11 = t10.^2;
t14 = t9+v;
t15 = R.*t12;
t18 = t13.*(t5-v);
t26 = t8.*theta3.*(t5-v);
t16 = abs(t14);
t17 = sign(t14);
t20 = dirac(t18);
t21 = sign(t18);
t24 = t10.*t16.*theta2;
t25 = t10.*t17.*theta2;
t27 = t4.*t11.*t16.*theta2;
t28 = -t24;
t30 = -t27;
t29 = exp(t28);
t34 = t25+t30;
t33 = R.*t25.*t29;
t37 = t29.*t34;
t36 = t15+t33;
t38 = t12+t26+t37;
mt1 = [-(Cd.*(v.*2.0-wind.*2.0))./m+t2.*t21.*t38.*theta1.*(9.81e+2./1.0e+2)-t2.*t20.*theta1.*(t7+t8.*(t5-v)).*(t29+t12.*(t5-v)-1.0).*(9.81e+2./5.0e+1),R.*m.*t2.*t6.*t21.*t38.*theta1.*(-9.81e+2./1.0e+2)+R.*m.*t2.*t6.*t20.*theta1.*(t7+t8.*(t5-v)).*(t29+t12.*(t5-v)-1.0).*(9.81e+2./5.0e+1),0.0,0.0,0.0,t2.*t21.*t36.*theta1.*(-9.81e+2./1.0e+2)+R.*t2.*t7.*t20.*theta1.*(t29+t12.*(t5-v)-1.0).*(9.81e+2./5.0e+1)];
mt2 = [R.*m.*t2.*t6.*t21.*t36.*theta1.*(9.81e+2./1.0e+2)-R.^2.*m.*t2.*t6.*t7.*t20.*theta1.*(t29+t12.*(t5-v)-1.0).*(9.81e+2./5.0e+1),0.0,0.0,0.0,t2.*t21.*(t29+t12.*(t5-v)-1.0).*(-9.81e+2./1.0e+2),R.*m.*t2.*t6.*t21.*(t29+t12.*(t5-v)-1.0).*(9.81e+2./1.0e+2),0.0,0.0,0.0,t2.*t10.*t16.*t21.*t29.*theta1.*(9.81e+2./1.0e+2),R.*m.*t2.*t6.*t10.*t16.*t21.*t29.*theta1.*(-9.81e+2./1.0e+2),0.0,0.0,0.0,t2.*t7.*t21.*theta1.*(t5-v).*(-9.81e+2./1.0e+2),R.*m.*t2.*t6.*t7.*t21.*theta1.*(t5-v).*(9.81e+2./1.0e+2),0.0,0.0,0.0];
A = reshape([mt1,mt2],5,5);
end
