function l = l_function(lambda0)
%L_FUNCTION
%    L = L_FUNCTION(LAMBDA0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Apr-2024 17:45:41

l = sign(lambda0).*(lambda0.*(1.3e+1./2.5e+1)+exp(abs(lambda0).*(-2.399e+1))-1.0).*(-3.1392e+3)+2.0283648e+3;
end
