function l = l_function(lambda0)
%L_FUNCTION
%    L = L_FUNCTION(LAMBDA0)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Apr-2023 17:00:30

l = lambda0.*(4.16e+2./6.25e+2)+exp(abs(lambda0).*2.399e+1).*(3.2e+1./2.5e+1)-1.362997548623853;
